version: "3.8"

services:
  user-app:
    image: onkar838/user-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - bank-server
      - webhook

  bank-server:
    image: onkar838/bank-server:latest
    ports:
      - "5001:5001"
    depends_on:
      - webhook

  webhook:
    image: onkar838/webhook:latest
    ports:
      - "5000:5000"

networks:
  default:
    driver: bridge
