name: Build Docker Image and Push to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Context for the build; ensure your Dockerfile and necessary files are in this context
          file: ./docker/Dockerfile.user-app
          push: true # Push the image to Docker Hub after building
          tags: onkar838/user-app:latest # Update with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull onkar838/user-app:latest
