# name: Build Docker Image and Push to Docker Hub
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check Out Repo
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: . # Context for the build; ensure your Dockerfile and necessary files are in this context
#           file: ./docker/Dockerfile.user-app
#           push: true # Push the image to Docker Hub after building
#           tags: onkar838/user-app:latest # Update with your Docker Hub username and repository

#       - name: Verify Pushed Image
#         run: docker pull onkar838/user-app:latest

#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             sudo docker pull onkar838/user-app:latest
#             sudo docker stop wallet-container || true
#             sudo docker rm wallet-container || true
#             sudo docker run -d --name wallet-container -p 3005:3000 onkar838/user-app:latest

name: Build Docker Image and Push to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push user-app image
      - name: Build and Push Docker image for user-app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user-app
          push: true
          tags: onkar838/user-app:latest

      # Build and push bank-server image
      - name: Build and Push Docker image for bank-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.bank-server
          push: true
          tags: onkar838/bank-server:latest

      # Build and push webhook image
      - name: Build and Push Docker image for webhook
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.webhook
          push: true
          tags: onkar838/webhook:latest

      - name: Verify Pushed Images
        run: |
          docker pull onkar838/user-app:latest
          docker pull onkar838/bank-server:latest
          docker pull onkar838/webhook:latest

      - name: Deploy to EC2 with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest images
            sudo docker-compose pull

            # Restart the services using docker-compose
            sudo docker-compose down
            sudo docker-compose up -d
